// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64       `json:"id"`
	Uid          pgtype.UUID `json:"uid"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Role         interface{} `json:"role"`
	PasswordHash string      `json:"password_hash"`
}
