// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateBrand(ctx context.Context, name string) (Brand, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateShippingRules(ctx context.Context, arg CreateShippingRulesParams) (ShippingRule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshTokenByUserID(ctx context.Context, userID int64) error
	GetRefreshTokenByID(ctx context.Context, tokenID string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
