// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (name,email,password_hash) values ('josephus kalizzy', 'jboss@example.com', 'chingege') returning id, uid, name, email, role, password_hash
`

func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}
